---

- hosts: all
  become: true
  tasks:
  
  - name: install httpd and php package
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes

  - name: enable httpd service
    service:
      name: httpd
      enabled: yes
      state: restarted

  - name: enable http service on firewalld
    ansible.posix.firewalld:
      zone: public
      service: http
      permanent: true
      state: enabled

  - name: reload firewalld
    service:
      name: firewalld
      state: reloaded
